### ISSUE TITLE
Redis module is missing after merge of circlesApi (PR #249)

### ISSUE THREAD

**Issue by assafSabag** [linnovate/root#250]
/home/abc/Desktop/root-fixes/node_modules/meanio/node_modules/q/q.js:151
                throw e;
                ^

Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/abc/Desktop/root-fixes/packages/custom/icu/server/controllers/circles.js:9:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/abc/Desktop/root-fixes/packages/core/users/server/controllers/users.js:15:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/abc/Desktop/root-fixes/packages/core/users/server/routes/users.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
abc@ubuntu:~/Desktop/root-fixes$

**Comment by kaplanlior** [comment]
Required by packages/custom/icu/server/controllers/circles.js ...

**Comment by kaplanlior** [comment]
redis isn't needed anymore due to 48860f5685850beb4e981eaf606b3edff77b8947.

But the issue itself was with npm-shrinkwrap (see 4856d4e9d09b9f98d93b819b31b01ca9e403167f).
