### ISSUE TITLE
Clicking on "Schedule discussion" button in discussion failed

### ISSUE THREAD

**Issue by dvorad** [linnovate/root#343]
http://icu.dev6.linnovate.net/discussions/all/57b1bae8588fcb0721d141ae/activities

![screenshot from 2016-08-22 15 14 59](https://cloud.githubusercontent.com/assets/10514414/17854440/5986b27e-687b-11e6-8465-4ae32af88550.png)

**Comment by rivkatzur** [comment]
Unhandled rejection Error: Missing binding /home/nodejs/icu/packages/custom/mail-templates/node_modules/node-sass/vendor/linux-x64-46/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x

Found bindings for the following environments:
  - Linux 64-bit with Node 0.10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/home/nodejs/icu/packages/custom/mail-templates/node_modules/node-sass/lib/index.js:15:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at renderSass (/home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/template-manager.js:114:14)
    at /home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/template-manager.js:64:22
    at render (/home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/template-manager.js:46:10)
    at renderFile (/home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/util.js:53:38)
    at /home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/email-template.js:170:30
From previous event:
    at EmailTemplate._renderStyle (/home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/email-template.js:162:14)
    at /home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/email-template.js:121:100
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at EmailTemplate.renderHtml (/home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/email-template.js:120:27)
    at EmailTemplate.render (/home/nodejs/icu/packages/custom/mail-templates/node_modules/email-templates/lib/email-template.js:146:46)
    at render (/home/nodejs/icu/packages/custom/icu/server/services/mail.js:25:19)
    at Object.exports.send (/home/nodejs/icu/packages/custom/icu/server/services/mail.js:46:10)
    at EventEmitter.<anonymous> (/home/nodejs/icu/packages/custom/icu/server/controllers/discussion.js:167:21)
    at EventEmitter.<anonymous> (/home/nodejs/icu/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Promise.safeEmit (/home/nodejs/icu/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.fulfill (/home/nodejs/icu/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
    at Promise.resolve (/home/nodejs/icu/node_modules/mongoose/lib/promise.js:113:23)
    at /home/nodejs/icu/node_modules/mongoose/lib/model.js:2148:23
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
POST /api/discussions/57b1bae8588fcb0721d141ae/schedule - - - - ms

**Comment by dvorad** [comment]
@liorkesos I can't continue with the automating testing because this bug.
