### ISSUE TITLE
app crush on update discussion

### ISSUE THREAD

**Issue by nevos** [linnovate/root#718]
root-app_1      | CRUD CREATE
root-app_1      | permissions createContent
root-app_1      | {"issue":"discussion","issueId":"5ace1c18b47c2a001189dac7","type":"updateStatus","status":"scheduled","prev":"new"}
root-app_1      | {}
root-app_1      | content create catch all case.
root-app_1      | {"issue":"discussion","issueId":"5ace1c18b47c2a001189dac7","type":"updateStatus","status":"scheduled","prev":"new","circles":{},"created":"2018-04-11T14:31:48.051Z","updated":"2018-04-11T14:31:48.051Z","creator":"5acdfd3e3b41ce001378119c","permissions":[{"id":"5acdfd3e3b41ce001378119c","level":"editor"}]}
root-app_1      | Elasticsearch DEBUG: 2018-04-11T14:31:48Z
root-app_1      |   starting request {
root-app_1      |     "method": "POST",
root-app_1      |     "path": "/update/update/5ace1c54b47c2a001189dae3",
root-app_1      |     "body": {
root-app_1      |       "__v": 0,
root-app_1      |       "issue": "discussion",
root-app_1      |       "issueId": "5ace1c18b47c2a001189dac7",
root-app_1      |       "type": "updateStatus",
root-app_1      |       "status": "scheduled",
root-app_1      |       "prev": "new",
root-app_1      |       "created": "2018-04-11T14:31:48.051Z",
root-app_1      |       "updated": "2018-04-11T14:31:48.051Z",
root-app_1      |       "creator": "5acdfd3e3b41ce001378119c",
root-app_1      |       "id": "5ace1c54b47c2a001189dae3"
root-app_1      |     },
root-app_1      |     "query": {}
root-app_1      |   }
root-app_1      |   
root-app_1      | 
root-app_1      | perms:
root-app_1      | [{"id":"5acdfd3e3b41ce001378119c","level":"editor"},{"id":"5acdaf4465b6180011814885","level":"commenter"}]
root-app_1      | update content - allowed
root-app_1      | Elasticsearch TRACE: 2018-04-11T14:31:48Z
root-app_1      |   -> POST http://172.18.0.4:9200/update/update/5ace1c54b47c2a001189dae3
root-app_1      |   {
root-app_1      |     "__v": 0,
root-app_1      |     "issue": "discussion",
root-app_1      |     "issueId": "5ace1c18b47c2a001189dac7",
root-app_1      |     "type": "updateStatus",
root-app_1      |     "status": "scheduled",
root-app_1      |     "prev": "new",
root-app_1      |     "created": "2018-04-11T14:31:48.051Z",
root-app_1      |     "updated": "2018-04-11T14:31:48.051Z",
root-app_1      |     "creator": "5acdfd3e3b41ce001378119c",
root-app_1      |     "id": "5ace1c54b47c2a001189dae3"
root-app_1      |   }
root-app_1      |   <- 201
root-app_1      |   {
root-app_1      |     "_index": "update",
root-app_1      |     "_type": "update",
root-app_1      |     "_id": "5ace1c54b47c2a001189dae3",
root-app_1      |     "_version": 1,
root-app_1      |     "result": "created",
root-app_1      |     "_shards": {
root-app_1      |       "total": 2,
root-app_1      |       "successful": 1,
root-app_1      |       "failed": 0
root-app_1      |     },
root-app_1      |     "created": true
root-app_1      |   }
root-app_1      | 
root-app_1      | Elasticsearch DEBUG: 2018-04-11T14:31:48Z
root-app_1      |   Request complete
root-app_1      | 
root-app_1      | /usr/src/app/packages/custom/icu/server/services/mail.js:61
root-app_1      |             logger.log('error', '%s writeDocxToFile, %s', req.user.name, ' convert-to pdf', {error: err.message});
root-app_1      |                                                           ^
root-app_1      | 
root-app_1      | ReferenceError: req is not defined
root-app_1      |     at /usr/src/app/packages/custom/icu/server/services/mail.js:61:59
root-app_1      |     at ChildProcess.exithandler (child_process.js:220:5)
root-app_1      |     at emitTwo (events.js:87:13)
root-app_1      |     at ChildProcess.emit (events.js:172:7)
root-app_1      |     at maybeClose (internal/child_process.js:854:16)
root-app_1      |     at Socket.<anonymous> (internal/child_process.js:330:11)
root-app_1      |     at emitOne (events.js:77:13)
root-app_1      |     at Socket.emit (events.js:169:7)
root-app_1      |     at Pipe._onclose (net.js:487:12)
root-app_1      | [14:31:50] [nodemon] app crashed - waiting for file changes before starting...

**Comment by nevos** [comment]
not reproducible
