### ISSUE TITLE
office signitures app crush

### ISSUE THREAD

**Issue by nevos** [linnovate/root#722]
@srayaAvraham note: 
https://github.com/linnovate/root/commit/4e78a5316f4839f4a65554418cb683a7cf796f9a#diff-c102ea56a9141d1822641ad3e0c75d80
(reported originally by @AviramAshkenazi ) I cannot reproduce it directly - but it relates to code you last visited, (notifications line 136)
TypeError: Cannot read property 'hasRoom' of null - probably cannot find the relevant project, and an error is ignored....

![image](https://user-images.githubusercontent.com/1281931/38665701-b766c91e-3e45-11e8-9ab4-ccd858d194b1.png)

root-app_1      |   starting request {
root-app_1      |     "method": "POST",
root-app_1      |     "path": "/office/office/5ace00e33b41ce00137811e9",
root-app_1      |     "body": {
root-app_1      |       "title": "<p>bndghdghd</p>",
root-app_1      |       "color": "0097A7",
root-app_1      |       "updated": "2018-04-12T08:18:03.200Z",
root-app_1      |       "creator": "5acdfd3e3b41ce001378119c",
root-app_1      |       "__v": 2,
root-app_1      |       "description": "nbjnv bbvcjh si",
root-app_1      |       "tel": "<p>&nbsp;vxfgxfgx</p>",
root-app_1      |       "unit": "<p>1564564</p>",
root-app_1      |       "WantRoom": true,
root-app_1      |       "sources": [],
root-app_1      |       "hasRoom": false,
root-app_1      |       "permissions": [
root-app_1      |         {
root-app_1      |           "id": "5acdfd3e3b41ce001378119c",
root-app_1      |           "level": "editor"
root-app_1      |         }
root-app_1      |       ],
root-app_1      |       "watchers": [
root-app_1      |         "5acdfd3e3b41ce001378119c"
root-app_1      |       ],
root-app_1      |       "status": "new",
root-app_1      |       "created": "2018-04-11T12:34:43.727Z",
root-app_1      |       "star": false,
root-app_1      |       "id": "5ace00e33b41ce00137811e9"
root-app_1      |     },
root-app_1      |     "query": {}
root-app_1      |   }
root-app_1      |   
root-app_1      | 
root-app_1      | events.js:141
root-app_1      |       throw er; // Unhandled 'error' event
root-app_1      |       ^
root-app_1      | 
root-app_1      | TypeError: Cannot read property 'hasRoom' of null
root-app_1      |     at /usr/src/app/packages/custom/icu/server/controllers/notification.js:136:25
root-app_1      |     at /usr/src/app/node_modules/mongoose/lib/query.js:3118:18
root-app_1      |     at newTickHandler (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:234:18)
root-app_1      |     at nextTickCallbackWith0Args (node.js:436:9)
root-app_1      |     at process._tickCallback (node.js:365:13)
root-app_1      | [08:18:03] [nodemon] app crashed - waiting for file changes before starting...

**Comment by nevos** [comment]
@ohadetsion did you manage to duplicate? any news?

**Comment by nevos** [comment]
not reproducible any more
